spring.application.name=skillshub

spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4jneo4j
spring.neo4j.uri=bolt://localhost:7687

logging.level.org.springframework.data.neo4j=DEBUG
logging.level.org.springframework.data.neo4j.cypher=trace

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG

# OAuth2 properties - O365
spring.security.oauth2.client.registration.azure.client-id=2ac3509e-7eaf-45d4-94eb-c7d9216b0b01
spring.security.oauth2.client.registration.azure.client-secret=***REMOVED_AZURE_CLIENT_SECRET***
microsoft.azure.tenant-id=b473afa3-9f94-440a-944f-7906ca9bd881
spring.mail.username=no-reply@mdr-tools.com

server.servlet.context-path=/api

# application.properties
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false  
# Set to true in production

skillhub.server = http://localhost:8080
skillhub.agent = http://localhost:8000