spring.application.name=skillshub
spring.neo4j.authentication.username=${NEO4J_USER}
spring.neo4j.authentication.password=${NEO4J_PASS}
spring.neo4j.uri=${NEO4J_URI}
logging.level.org.springframework.data.neo4j=DEBUG
logging.level.org.springframework.data.neo4j.cypher=trace
# server.error.include-message=always
# server.error.include-binding-errors=always
# server.error.include-stacktrace=always
# server.error.include-exception=true
# logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
# OAuth2 properties - O365
spring.security.oauth2.client.registration.azure.client-id=${OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.azure.client-secret=${OAUTH_CLIENT_SECRET}
microsoft.azure.tenant-id=${AZURE_TENANT_ID}
spring.mail.username=no-reply@mdr-tools.com
skillhub.server=http://localhost:8080
server.servlet.context-path=/api