name: Backend Deployment

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      IMAGE_TAG: backend_${{ github.sha }}

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.DEPLOYMENT_PAT }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to Backend EC2
        uses: appleboy/ssh-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: eu-west-3
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BACKEND_NEO4J_USER: ${{ secrets.NEO4J_USER }}
          BACKEND_NEO4J_PASS: ${{ secrets.NEO4J_PASS }}
          BACKEND_NEO4J_URI: ${{ secrets.NEO4J_URI }}
          BACKEND_OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          BACKEND_OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          BACKEND_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AGENT_URI: ${{ vars.AGENT_URI }}

        with:
          envs: ECR_REGISTRY,ECR_REPOSITORY,IMAGE_TAG,AWS_ACCOUNT_ID,AWS_REGION,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,BACKEND_NEO4J_USER,BACKEND_NEO4J_PASS,BACKEND_NEO4J_URI,BACKEND_OAUTH_CLIENT_ID,BACKEND_OAUTH_CLIENT_SECRET,BACKEND_AZURE_TENANT_ID,AGENT_URI
          host: ${{ secrets.BACKEND_EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          proxy_host: ${{ secrets.FRONTEND_EC2_HOST }}
          proxy_username: ${{ secrets.EC2_USERNAME }}
          proxy_key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop backend || true
            docker rm backend || true
            aws configure set aws_access_key_id > echo $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key > echo $AWS_SECRET_ACCESS_KEY
            aws configure set default.region > echo $AWS_REGION
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker run -d \
              --name backend \
              -p 3080:8080 \
              -v /skillshub/data/profile:/profile \
              -v /skillshub/data/project:/project \
              --env NEO4J_USER=$BACKEND_NEO4J_USER \
              --env NEO4J_PASS=$BACKEND_NEO4J_PASS \
              --env NEO4J_URI=$BACKEND_NEO4J_URI \
              --env OAUTH_CLIENT_ID=$BACKEND_OAUTH_CLIENT_ID \
              --env OAUTH_CLIENT_SECRET=$BACKEND_OAUTH_CLIENT_SECRET \
              --env AZURE_TENANT_ID=$BACKEND_AZURE_TENANT_ID \
              --env AGENT_URI=$AGENT_URI \
              --restart always \
              --network skillshub_backend_network \
              $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG